import type { AppData } from "@/types/domain";

const now = new Date().toISOString();

export const demoData: AppData = {
  organizations: [
    {
      id: "org_demo",
      name: "Dealer Flow Demo",
      role: "owner",
      inviteCode: "DEALER-2026",
      defaultPlateCommissionAmount: 250,
    },
    {
      id: "org_viewer",
      name: "Partner Dashboard",
      role: "viewer",
      inviteCode: "PARTNER-READ",
      defaultPlateCommissionAmount: 250,
    },
  ],
  activeOrganizationId: "org_demo",
  userName: "Kirolos",
  vehicles: [
    {
      id: "veh_1",
      organizationId: "org_demo",
      vin: "2HGFC2F59KH000001",
      year: 2019,
      make: "Honda",
      model: "Civic",
      trim: "LX",
      color: "Gray",
      mileage: 84200,
      purchasePrice: 9200,
      purchaseDate: "2026-01-12",
      purchaseSource: "OpenLane",
      status: "listed_for_sale",
      listedPrice: 13500,
      notes: "Clean interior, inspection booked.",
      mainPhotoUrl: "",
      createdAt: now,
      updatedAt: now,
      createdBy: "demo_user",
    },
    {
      id: "veh_2",
      organizationId: "org_demo",
      vin: "1C4RJFBG8HC000002",
      year: 2017,
      make: "Jeep",
      model: "Grand Cherokee",
      trim: "Limited",
      color: "Black",
      mileage: 126000,
      purchasePrice: 11800,
      purchaseDate: "2026-02-03",
      purchaseSource: "Copart",
      status: "in_repair",
      listedPrice: 16900,
      notes: "Front bumper repair in progress.",
      mainPhotoUrl: "",
      createdAt: now,
      updatedAt: now,
      createdBy: "demo_user",
    },
    {
      id: "veh_3",
      organizationId: "org_demo",
      vin: "3VW167AJ9HM000003",
      year: 2017,
      make: "Volkswagen",
      model: "Jetta",
      trim: "Trendline",
      color: "White",
      mileage: 101500,
      purchasePrice: 6400,
      purchaseDate: "2026-01-04",
      purchaseSource: "dealerAuction",
      status: "sold",
      listedPrice: 9900,
      notes: "Sold to repeat buyer.",
      createdAt: now,
      updatedAt: now,
      createdBy: "demo_user",
    },
  ],
  expenses: [
    {
      id: "exp_1",
      organizationId: "org_demo",
      vehicleId: "veh_1",
      category: "vehicle_purchase_price",
      amountBeforeTax: 9200,
      taxRate: 0.05,
      taxAmount: 460,
      totalAmount: 9660,
      date: "2026-01-12",
      note: "OpenLane purchase price tax.",
      createdAt: now,
      createdBy: "demo_user",
    },
    {
      id: "exp_2",
      organizationId: "org_demo",
      vehicleId: "veh_1",
      category: "auction_fee",
      amountBeforeTax: 495,
      taxRate: 0.15,
      taxAmount: 74.25,
      totalAmount: 569.25,
      date: "2026-01-12",
      note: "OpenLane auction fee.",
      createdAt: now,
      createdBy: "demo_user",
    },
    {
      id: "exp_3",
      organizationId: "org_demo",
      vehicleId: "veh_2",
      category: "repair",
      amountBeforeTax: 1450,
      taxRate: 0.15,
      taxAmount: 217.5,
      totalAmount: 1667.5,
      date: "2026-02-07",
      note: "Body repair deposit.",
      createdAt: now,
      createdBy: "demo_user",
    },
    {
      id: "exp_4",
      organizationId: "org_demo",
      vehicleId: "veh_3",
      category: "inspection",
      amountBeforeTax: 180,
      taxRate: 0.15,
      taxAmount: 27,
      totalAmount: 207,
      date: "2026-01-09",
      note: "Inspection before sale.",
      createdAt: now,
      createdBy: "demo_user",
    },
  ],
  sales: [
    {
      id: "sale_1",
      organizationId: "org_demo",
      vehicleId: "veh_3",
      contactId: "contact_1",
      saleDate: "2026-02-18",
      vehicleTotalCost: 6607,
      taxableProfitAmount: 1900,
      profitTaxDue: 418,
      paperSalePrice: 8507,
      realClientPayment: 9300,
      externalCommission: 793,
      notes: "Paper sale and external commission tracked separately.",
      createdAt: now,
      createdBy: "demo_user",
    },
  ],
  contacts: [
    {
      id: "contact_1",
      organizationId: "org_demo",
      type: "buyer",
      fullName: "Marc Tremblay",
      phone: "514-555-0144",
      email: "marc@example.com",
      address: "Montreal, QC",
      notes: "Bought the Jetta. Potential future SUV buyer.",
      createdAt: now,
      updatedAt: now,
      createdBy: "demo_user",
    },
    {
      id: "contact_2",
      organizationId: "org_demo",
      type: "export_contact",
      fullName: "Amina Export",
      phone: "438-555-0190",
      exportRegion: "West Africa",
      desiredVehicleTypes: "Toyota, Honda, clean SUVs",
      preferredCommunicationMethod: "WhatsApp",
      notes: "Interested in export-ready vehicles.",
      createdAt: now,
      updatedAt: now,
      createdBy: "demo_user",
    },
  ],
  attachments: [
    {
      id: "att_1",
      organizationId: "org_demo",
      type: "link",
      title: "Marketplace listing",
      urlOrPath: "https://example.com/listing",
      vehicleId: "veh_1",
      isSensitive: false,
      createdAt: now,
      createdBy: "demo_user",
    },
    {
      id: "att_2",
      organizationId: "org_demo",
      type: "file",
      title: "Driver license photo metadata",
      urlOrPath: "private://contacts/contact_1/license.jpg",
      contactId: "contact_1",
      isSensitive: true,
      notes: "Private storage only. No public URL.",
      createdAt: now,
      createdBy: "demo_user",
    },
  ],
  companyCashTransactions: [
    {
      id: "cct_1",
      organizationId: "org_demo",
      type: "company_cash_added",
      amount: 25000,
      date: "2026-01-01",
      note: "Opening company cash.",
      createdAt: now,
      createdBy: "demo_user",
    },
    {
      id: "cct_2",
      organizationId: "org_demo",
      type: "vehicle_cost_paid",
      amount: 9660,
      date: "2026-01-12",
      sourceVehicleId: "veh_1",
      note: "Honda purchase cost paid.",
      createdAt: now,
      createdBy: "demo_user",
    },
    {
      id: "cct_3",
      organizationId: "org_demo",
      type: "paper_sale_received",
      amount: 8507,
      date: "2026-02-18",
      sourceVehicleId: "veh_3",
      note: "Paper sale received.",
      createdAt: now,
      createdBy: "demo_user",
    },
  ],
  externalCashTransactions: [
    {
      id: "ect_1",
      organizationId: "org_demo",
      type: "external_commission_earned",
      amount: 793,
      date: "2026-02-18",
      sourceVehicleId: "veh_3",
      note: "External commission from Jetta sale.",
      createdAt: now,
      createdBy: "demo_user",
    },
    {
      id: "ect_2",
      organizationId: "org_demo",
      type: "external_cash_transferred_to_company",
      amount: 300,
      date: "2026-02-20",
      note: "Transparent transfer into company cash.",
      createdAt: now,
      createdBy: "demo_user",
    },
  ],
  activityLogs: [
    {
      id: "log_1",
      organizationId: "org_demo",
      action: "vehicle_created",
      entityType: "vehicle",
      entityId: "veh_1",
      message: "Honda Civic created.",
      createdAt: "2026-01-12T10:00:00.000Z",
      createdBy: "demo_user",
    },
    {
      id: "log_2",
      organizationId: "org_demo",
      action: "sale_recorded",
      entityType: "sale",
      entityId: "sale_1",
      message: "Volkswagen Jetta sale recorded.",
      createdAt: "2026-02-18T14:30:00.000Z",
      createdBy: "demo_user",
    },
  ],
};
